### ISSUE TITLE
collection.find is very slow and get_by_uuid is deprecated

### ISSUE THREAD

**Issue by fmbiete** [fog/fog-xenserver#43]
This code is very slow when used in a big pool +150 servers
```
connection.servers.find { |server| server.uuid == vm_uuid }
```

This method is a lot faster, but it's deprecated?
```
connection.servers.get_by_uuid(vm_uuid)
```
The shown message is pretty confusing:
```
[fog][DEPRECATION] This method is deprecated. Use #get_by_uuid instead.
```

**Comment by plribeiro3000** [comment]
Are you sure are you using `fog-xenserver` and not `fog` itself?

If you take a look at [this line](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server/models/collection.rb#L28) you will see the methods does not raise any warning and the request implementation [here](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server/requests/get_record.rb#L17) does not also.

In the main `Fog` gem this method is defined [here](https://github.com/fog/fog/blob/master/lib/fog/xenserver/models/compute/servers.rb#L49) and it calls the method [`get_vm_by_uuid`](https://github.com/fog/fog/blob/master/lib/fog/xenserver/requests/compute/create_server.rb#L12) that is raising the exception because it is deprecated.

Just use the `fog-xenserver` and you are good to go. LMK if it does not work for you. Thank!

**Comment by fmbiete** [comment]
OMG!!! silly me, xenserver module inside fog is not fog-xenserver... I have update my gemfile to include this, and the deprecation warning is gone.

Thanks!!

**Comment by plribeiro3000** [comment]
You are welcome! That was kind of a lack of documentation issue.

We are going to remove the support in `fog` and add `fog-xenserver` as dependency soon. Until that try to use `fog-xenserver` instead. =)
