### ISSUE TITLE
vhd LVM sr

### ISSUE THREAD

**Issue by raidxx** [fog/fog-xenserver#52]
there is no way to affect vhd to VDI created on LVM storage repo ?
 this is my case : https://github.com/bvox/fog-xenserver-examples/blob/master/create_vm_advanced_hvm.rb

**Comment by plribeiro3000** [comment]
Hey @raidxx, whats up?

Which part of that code exactly do you mean?

[This](https://github.com/bvox/fog-xenserver-examples/blob/master/create_vm_advanced_hvm.rb#L30-L77) part of the code seems to be pretty fine to me. It should work as intended with a few differences.

Can you be more precise on what is you error? expected behavior?

**Comment by plribeiro3000** [comment]
Closing due lack of feedback.

Please comment over again if you still have this error.
